config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resource :session, only: [:new, :create, :destroy]

  resources :subs

  resources :posts, except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, :author_id, :subs, presence: true

  has_many :post_subs,
    dependent: :destroy,
    inverse_of: :post

  has_many :subs,
    through: :post_subs


  belongs_to :author,
    class_name: :User
end

app/models/post_sub.rb
class PostSub < ApplicationRecord
  validates :post, :sub, presence: true
  validates :post, uniqueness: { scope: :sub }

  belongs_to :post, inverse_of: :post_subs
  belongs_to :sub
end

app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :text
#  moderator_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :moderator_id, presence: true
  validates :title, uniqueness: { scope: :moderator_id}

  has_many :post_subs,
    dependent: :destroy

  has_many :posts,
    through: :post_subs,
    source: :post,
    dependent: :destroy

  belongs_to :moderator,
    class_name: :User
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :username, uniqueness: true

  after_initialize :ensure_session_token
  attr_reader :password

  has_many :subs,
    foreign_key: :moderator_id

  has_many :posts,
    foreign_key: :author_id

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_random_token
  end

  def self.generate_random_token
    SecureRandom.urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if user && user.valid_password?(password)
    nil
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_random_token
    self.save!
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def login(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login
  before_action :post_author?, only: [:edit, :update, :destroy]

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def new
    @post = Post.new()
    render :new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to sub_url(post.sub)
  end

  def post_author?
    post = Post.find(params[:id])
    redirect_to post_url(post) unless post.author == current_user
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password])

    if user
      login(user)
      redirect_to subs_url
    else
      flash.now[:errors] = ['Invalid Credentials']
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login
  before_action :sub_moderator?, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @subforum = Sub.find(params[:id])
    render :show
  end

  def edit
    @subforum = Sub.find(params[:id])
    render :edit
  end

  def update
    @subforum = Sub.find(params[:id])

    if @subforum.update(sub_params)
      redirect_to sub_url(@subforum)
    else
      flash.now[:errors] = @subforum.errors.full_messages
      render :edit
    end
  end

  def new
    @subforum = Sub.new
    render :new
  end

  def create
    @subforum = Sub.new(sub_params)
    @subforum.moderator = current_user
    if @subforum.save
      redirect_to sub_url(@subforum)
    else
      flash.now[:errors] = @subforum.errors.full_messages
      render :new
    end
  end

  def destroy
    subforum = Sub.find(params[:id])
    subforum.destroy
    redirect_to subs_url
  end

  def sub_moderator?
    subforum = Sub.find(params[:id])
    redirect_to sub_url(subforum) unless subforum.moderator == current_user
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to subs_url
    else
      flash.now[:errors] = user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\"
    name=\"authenticity_token\"
    value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join('<br>').html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit-Lite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <h1>Reddit-Lite</h1>
    <%= render 'layouts/errors' %>
    <% if logged_in? %>
      <form action="<%= session_url %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Sign Out">
      </form>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% destination = @post.persisted? ? post_url(@post) : posts_url %>

<form  action="<%= destination %>" method="POST">
  <%= auth_token %>
  <% if @post.persisted?  %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>
  <br>
  <br>
  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>
  <br>
  <br>
  Content
  <br>
  <textarea name="post[content]" rows="8" cols="80">
<%=@post.content %>
  </textarea>
  <br>
  <ul>
    <% Sub.all.each do |sub| %>
    <li>

      <label><%= sub.title %>
        <input type="checkbox"
               name="post[sub_ids][]"
               value="<%= sub.id %>"
               <%= "checked" if @post.sub_ids.include?(sub.id) %> >
      </label>
    </li>

    <% end %>
  </ul>
  <input type="submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<br>
<%  owner = @post.author == current_user %>
<a href="<%= subs_url %>">Back to Forum Index</a>
<br>
<br>

<% if owner %>
  <a href="<%= edit_post_url(@post) %>">Edit Post</a>
<% end %>

<a href="<%= @post.url %>"><h2><%= @post.title %></h2> </a>
<% if owner %>
  <form class="" action="<%= post_url(@post) %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="delete">
    <input type="submit" name="" value="Delete">
  </form>
<% end %>
<h3>Content:</h3>
<p> <%= @post.content %> </p>

app/views/subs/_form.html.erb
<% destination = @subforum.persisted? ? sub_url(@subforum) : subs_url %>

<form  action="<%= destination %>" method="POST">
  <%= auth_token %>

  <% if @subforum.persisted?  %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label>Title
    <input type="text" name="sub[title]" value="<%= @subforum.title %>">
  </label>
  <br>
  <br>
  Description
  <br>
  <textarea name="sub[description]" rows="8" cols="80">
<%=@subforum.description %>
  </textarea>
  <br>

  <input type="submit" value="Submit">
</form>

app/views/subs/_sub.html.erb
<ul>
  <li>
    <a href="<%= sub_url(sub) %>">
      <h3><%= sub.title %></h3>
    </a>
  </li>
</ul>

app/views/subs/edit.html.erb
<h2>Edit Forum</h2>

<%= render 'form' %>

app/views/subs/index.html.erb
<h2>Forums</h2>

<a href="<%= new_sub_url %>">New Forum</a>
<br>
<br>

<ul>
  <%= render @subs %>
</ul>

app/views/subs/new.html.erb
<h2>New Forum</h2>

<%= render 'form' %>

app/views/subs/show.html.erb
<br>

<a href="<%= subs_url %>">All Forums</a>
<br>
<br>

<% if @subforum.moderator == current_user %>
  <a href="<%= edit_sub_url(@subforum) %>">Edit Forum</a>
<% end %>

<h2><%= @subforum.title %></h2>

<h3>Description:</h3>

<p> <%= @subforum.description %> </p>

<a href="<%= new_post_url %>">Add Post</a>
<br>
<br>

<ul>
<% @subforum.posts.each do |post| %>
  <li>
  <a href="<%= post_url(post) %>">
    <%= post.title %>
  </a>

  <% if @subforum.moderator == current_user %>
    <form class="" action="<%= post_url(post) %>" method="post">
      <%= auth_token %>
      <input type="hidden" name="_method" value="delete">
      <input type="submit" name="" value="Delete">
    </form>
  <% end %>
</li>
<br>
<% end %>
</ul>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<a href="<%= new_session_url %>">Already have an account? Sign in!</a>
<br>
<br>

<form class="" action="<%= users_url %>" method="post">
  <%= auth_token %>
  <label for="">
    Username
    <input type="text" name="user[username]" >
  </label>
    <br>
  <label for="">
    Password
    <input type="password" name="user[password]" >
  </label>
  <br>
  <input type="submit" value="Sign Up!">
</form>